    create table if not exists categories (
       id integer generated by default as identity,
        description varchar(100) not null unique,
        primary key (id)
    );

    create table suggestions (
       id integer generated by default as identity,
        data date,
        description varchar(500) not null,
        category_id integer,
        primary key (id)
    );

 alter table suggestions
       add constraint fk_category_suggestion foreign key(category_id) references categories(id);


insert into categories (description) values
('Sugestão'),
('Crítica'),
('Elogio'),
('Comentário');

insert into suggestions (data, description, category_id) values
('2023-05-27', 'Lorem ipsum dolor sit amet.', 4);